spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/taxi_management?useSSL=false&serverTimezone=UTC
    username: root # Thay bằng username MySQL của bạn
    password: 120404 # Thay bằng password MySQL của bạn
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Cấu hình Spring Data JPA và Hibernate
  jpa:
    hibernate:
      # update: Hibernate sẽ tự động tạo/cập nhật bảng dựa trên Entity
      ddl-auto: update
    show-sql: true # Hiển thị các câu lệnh SQL được sinh ra
    properties:
      hibernate:
        # Đảm bảo Hibernate biết bạn đang dùng MySQL
        dialect: org.hibernate.dialect.MySQLDialect

# Cấu hình cổng chạy ứng dụng (Mặc định là 8080)
server:
  port: 8080
